server:
  port: 9500

spring:
  application:
    name: nacos-question-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.229.51.73:3306/onlineexam?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Hx947769582..
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.onlineexam.entities

management:
  endpoints:
    web:
      exposure:
        include: '*'

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql