server:
  port: 84

spring:
  application:
    name: nacos-question-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#消费者将要去访问的服务名称
service-url:
  nacos-user-service: http://nacos-question-provider

ifCloseSwagger: true