server:
  port: 85

spring:
  application:
    name: nacos-score-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#消费者将要去访问的服务名称
service-url:
  nacos-user-service: http://nacos-score-provider